version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    ports:
      - "8000:8000"
    command: python src/app.py
